#+title:      cfa program overview
#+date:       [2025-07-04 Fri 21:52]
#+filetags:   :cfa:
#+identifier: 20250704T215227

* Brochure                                                           :ATTACH:
:PROPERTIES:
:ID:       bd0e15e1-238a-43c3-b463-67792b01e15f
:END:

* Introduction
CFA: Chartered Financial Analyst

The CFA Program is a three-part exam that tests the fundamentals of investment tools, valuation across various asset classes, portfolio construction, and ethical and professional standards.

* WHAT IS KEY TO EXAM SUCCESS?
** 300 HOURS
On average, candidates spend 300 hours of study per exam level, plus completion of mandatory
Practical Skills Module (PSM).
** EXAM PREP
All exam questions are based on CFA Program curriculum.
** STUDY TOOLS
- Online Learning Ecosystem
- practice questions
- mock exams
- candidate discussion board
- CFA Institute Learning App
- optional practice packs and prep courses
** 4+ YEARS
On average, it takes four years to complete the full program, including work experience requirements.
* STUDY MATERIALS
Passing the three exams marks true mastery of the curriculum and is the most important task
required to earn the CFA® charter.

On average, candidates report investing over 300 hours of study in advance of successfully passing each level.

Becoming a CFA charterholder takes hard work and commitment.

When you are a candidate, complete support is provided through the Learning Ecosystem, that helps candidates to prepare for the exam, available online and as an app.

CFA Institute provides candidates with access to a wealth of information that will help them to pass the CFA exams and excel in their career.

* STUDY TOOLS: LEARNING ECOSYSTEM
CFA Institute provides the full curriculum in a comprehensive digital Learning Ecosystem to
all registered candidates.

It includes practice questions, mock exams, and more.

* OPTIONAL PRACTICE PACKS
Practice Packs are available for all three exam levels and include a suite of additional prep
materials, such as extra practice questions, exam day experience and mock exams from the
authors of the CFA Program.

They are available for purchase either at registration or at anytime before your exam day.
* PSM
A Practical Skills Module (PSM) uses a combination of videos, multiple-choice questions, guided practice, and case studies to develop candidates’ practical skills.

In order to receive their exam result, candidates are required to complete at least one PSM at each level.

The PSM topic may be chosen after registration at any time during your exam study period and must be completed before results are released. Each PSM takes 10-20 hours to complete.

