#+title:      apple 2024q4 financial data
#+date:       [2025-07-12 Sat 19:01]
#+filetags:   :cfa:
#+identifier: 20250712T190139

* Financial Statements                                               :ATTACH:
:PROPERTIES:
:ID:       9652622d-c42e-4578-8b46-071857d0717d
:END:

** Press release
CUPERTINO, CALIFORNIA Apple today announced financial results for its fiscal 2024 fourth quarter ended September 28, 2024. The Company posted quarterly revenue of $94.9 billion, up 6 percent year over year, and quarterly diluted earnings per share of $0.97. Diluted earnings per share was $1.64,1 up 12 percent year over year when excluding the one-time charge recognized during the fourth quarter of 2024 related to the impact of the reversal of the European General Court’s State Aid decision.

“Today Apple is reporting a new September quarter revenue record of $94.9 billion, up 6 percent from a year ago,” said Tim Cook, Apple’s CEO. “During the quarter, we were excited to announce our best products yet, with the all-new iPhone 16 lineup, Apple Watch Series 10, AirPods 4, and remarkable features for hearing health and sleep apnea detection. And this week, we released our first set of features for Apple Intelligence, which sets a new standard for privacy in AI and supercharges our lineup heading into the holiday season.”

“Our record business performance during the September quarter drove nearly $27 billion in operating cash flow [fn:1], allowing us to return over $29 billion to our shareholders,” said Luca Maestri, Apple’s CFO. “We are very pleased that our active installed base of devices reached a new all-time high across all products and all geographic segments, thanks to our high levels of customer satisfaction and loyalty.”

Apple’s board of directors has declared a cash dividend of $0.25 per share of the Company’s common stock. The dividend is payable on November 14, 2024 to shareholders of record as of the close of business on November 11, 2024.

* Footnotes

[fn:1] Operating cash flow (OCF) is the actual cash generated from Apple's core business operations, not including investments or financing. 

* 10-K                                                               :ATTACH:
:PROPERTIES:
:ID:       dd4c1108-8383-468d-932a-e46f247a9eaf
:END:
